# Generated by Django 5.0.3 on 2025-12-16 07:49

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band',
            fields=[
                ('band_id', models.AutoField(primary_key=True, serialize=False)),
                ('band_name', models.CharField(max_length=100)),
                ('genre', models.CharField(choices=[('rock', 'Rock'), ('pop', 'Pop'), ('jazz', 'Jazz'), ('blues', 'Blues'), ('classical', 'Classical'), ('electronic', 'Electronic'), ('folk', 'Folk'), ('metal', 'Metal'), ('punk', 'Punk'), ('reggae', 'Reggae'), ('hip-hop', 'Hip-Hop'), ('country', 'Country'), ('funk', 'Funk'), ('soul', 'Soul'), ('r&b', 'R&B'), ('alternative', 'Alternative'), ('indie', 'Indie'), ('hard_rock', 'Hard Rock'), ('progressive', 'Progressive'), ('house', 'House'), ('techno', 'Techno')], max_length=50)),
                ('founded_date', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'bands',
            },
        ),
        migrations.CreateModel(
            name='Concert',
            fields=[
                ('concert_id', models.AutoField(primary_key=True, serialize=False)),
                ('concert_title', models.CharField(max_length=200)),
                ('venue_address', models.CharField(max_length=255)),
                ('concert_date', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'concerts',
            },
        ),
        migrations.CreateModel(
            name='Musician',
            fields=[
                ('musician_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message='Phone must be in format +375XXXXXXXXX', regex='^\\+375[0-9]{9}$')])),
                ('telegram', models.CharField(blank=True, max_length=100, null=True, validators=[django.core.validators.RegexValidator(message='Telegram must start with @', regex='^@.+')])),
                ('instrument', models.CharField(choices=[('guitar', 'Guitar'), ('bass', 'Bass'), ('drums', 'Drums'), ('keyboards', 'Keyboards'), ('piano', 'Piano'), ('vocals', 'Vocals'), ('violin', 'Violin'), ('cello', 'Cello'), ('trumpet', 'Trumpet'), ('saxophone', 'Saxophone'), ('trombone', 'Trombone'), ('flute', 'Flute'), ('clarinet', 'Clarinet'), ('accordion', 'Accordion'), ('harp', 'Harp')], max_length=50)),
            ],
            options={
                'db_table': 'musicians',
            },
        ),
        migrations.CreateModel(
            name='Performance',
            fields=[
                ('performance_id', models.AutoField(primary_key=True, serialize=False)),
                ('performance_order', models.PositiveIntegerField()),
                ('band', models.ForeignKey(db_column='band_id', on_delete=django.db.models.deletion.CASCADE, to='core.band')),
                ('concert', models.ForeignKey(db_column='concert_id', on_delete=django.db.models.deletion.CASCADE, to='core.concert')),
            ],
            options={
                'db_table': 'performances',
            },
        ),
        migrations.CreateModel(
            name='Rehearsal',
            fields=[
                ('rehearsal_id', models.AutoField(primary_key=True, serialize=False)),
                ('rehearsal_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('duration_minutes', models.PositiveIntegerField()),
                ('location', models.CharField(max_length=255)),
                ('band', models.ForeignKey(db_column='band_id', on_delete=django.db.models.deletion.CASCADE, to='core.band')),
            ],
            options={
                'db_table': 'rehearsals',
            },
        ),
        migrations.CreateModel(
            name='BandMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('join_date', models.DateField(default=django.utils.timezone.now)),
                ('band', models.ForeignKey(db_column='band_id', on_delete=django.db.models.deletion.CASCADE, to='core.band')),
                ('musician', models.ForeignKey(db_column='musician_id', on_delete=django.db.models.deletion.CASCADE, to='core.musician')),
            ],
            options={
                'db_table': 'band_membership',
                'unique_together': {('band', 'musician')},
            },
        ),
    ]
