# Generated by Django 5.2.9 on 2025-12-25 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='band',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='band_logos/', verbose_name='Логотип'),
        ),
    ]
