# Generated by Django 5.2.9 on 2025-12-25 23:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('for_authorization', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='musicianuser',
            name='role',
            field=models.CharField(choices=[('viewer', 'Зритель'), ('musician', 'Музыкант'), ('manager', 'Менеджер группы'), ('venue_owner', 'Владелец площадки')], default='viewer', max_length=20, verbose_name='Роль пользователя'),
        ),
        migrations.AddField(
            model_name='musicianuser',
            name='venue_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес площадки'),
        ),
        migrations.AddField(
            model_name='musicianuser',
            name='venue_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название площадки'),
        ),
    ]
