# Generated by Django 5.2.9 on 2025-12-16 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Band_membership',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('band_id', models.IntegerField(verbose_name='Band id')),
                ('musician_id', models.IntegerField(verbose_name='Musician id')),
                ('join_date', models.DateTimeField(verbose_name='Joined')),
            ],
            options={
                'db_table': 'band_membership',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Bands',
            fields=[
                ('band_id', models.AutoField(db_column='band_id', primary_key=True, serialize=False)),
                ('band_name', models.CharField(max_length=100, verbose_name='Band name')),
                ('genre', models.CharField(max_length=50, verbose_name='Genre')),
                ('founded_date', models.DateTimeField(verbose_name='Founded')),
            ],
            options={
                'db_table': 'bands',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Concerts',
            fields=[
                ('concert_id', models.AutoField(db_column='concert_id', primary_key=True, serialize=False)),
                ('concert_title', models.CharField(max_length=200, verbose_name='Title')),
                ('venue_address', models.CharField(max_length=255, verbose_name='Address')),
                ('concert_date', models.DateTimeField(verbose_name='Date')),
            ],
            options={
                'db_table': 'concerts',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Musicians',
            fields=[
                ('musician_id', models.AutoField(db_column='musician_id', primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50, verbose_name='First name')),
                ('last_name', models.CharField(max_length=50, verbose_name='Last name')),
                ('phone', models.CharField(max_length=20, verbose_name='Phone')),
                ('telegram', models.CharField(max_length=100, verbose_name='Telegram')),
                ('instrument', models.CharField(max_length=100, verbose_name='Instrument')),
            ],
            options={
                'db_table': 'musicians',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Performances',
            fields=[
                ('performance_id', models.AutoField(db_column='performance_id', primary_key=True, serialize=False)),
                ('band_id', models.IntegerField(verbose_name='Band id')),
                ('concert_id', models.IntegerField(verbose_name='Concert id')),
                ('performance_order', models.IntegerField(verbose_name='Performance order')),
            ],
            options={
                'db_table': 'performances',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Rehearsals',
            fields=[
                ('rehearsal_id', models.AutoField(db_column='rehearsal_id', primary_key=True, serialize=False)),
                ('band_id', models.IntegerField(verbose_name='band id')),
                ('rehearsal_date', models.DateTimeField(verbose_name='Date & time')),
                ('duration_minutes', models.IntegerField(verbose_name='Duration minutes')),
                ('location', models.CharField(max_length=255, verbose_name='Location')),
            ],
            options={
                'db_table': 'rehearsals',
                'managed': False,
            },
        ),
    ]
